
* norns midigrid library 
  A few helper scripts for emulating and using midi grids like a monome grid, on the monome norns.

  Two scripts in the lib folder to include in scripts as 'grid', config files in the config folder for setups with different devices.
** instructions
   ~midigrid.lua~ and ~apcmini_config.lua~ is documented in the scripts themselves, setting up a new config file also means it needs to be loaded into the script itself:
 #+BEGIN_SRC lua 
-----------------------------
--loading up config file here
-----------------------------
local config = include('midigrid/config/apcmini_config')
-- local config = include('midigrid/config/launchpad_config')
-- local config = include('midigrid/config/untz_config')
-----------------------------
 #+END_SRC

Then, in whatever script you are working in, it works well to override the global grid object with our own local one:
#+BEGIN_SRC lua
    --adding this to script
    local grid = include('cheapskate/lib/midigrid')
    --or this
    local grid = include('cheapskate/lib/midigrid_2pages')
    --which allows this call to work with our midi grid
    local g = grid.connect()
#+END_SRC

Previous issues with the midi device being blocked are resolved with this new implementation taken from ryanlaws [https://github.com/ryanlaws/lunchpaid][lunchpaid].
** two page mode
   This script aims to emulate a 128 (16x8) grid by spreading a virtual grid buffer over two grid pages that you can toggle with auxiliary buttons
*** apc mini
    By default, the left and right arrow buttons on the bottom row of buttons on the grid
*** launchpad
    The toggle buttons are the top two column buttons in launchpad auxiliary column.  need to set them up so they can be the left and right arrows but this is non trivial as the top auxiliary buttons on the launchpad send control (176) messages not note on.
** todos
*** TODO add config files for launchpad (and untz maybe)
*** TODO allow config files to overide led and all functions, for more native launchpad support
*** DONE add cols and rows function 
    CLOSED: [2019-11-13 Wed 17:58]
*** DONE make page changing more efficient code wise
    CLOSED: [2019-11-18 Mon 11:27]
*** DONE consider how to make this more sensible with the midi device number thing... 
    CLOSED: [2019-11-18 Mon 11:27]
** scripts
   Notes for norns scripts that either work or I wanna make work, or need a little love to make work
*** step
    works, need to block out midi
*** strum
    works but with midi blocking
*** mlr64
    [https://github.com/noiserock/custom64][mlr64]
    works!
*** earthsea for apc mini
**** this is pretty much ready to go, use the earthsea from the ash library
     its glitchy and not sure why
     working but glitchy?
*** vials for apc mini
**** I think this can be implemented as just split view toggle
     if view2 then {new mapping}
**** status
     works pretty great two pages
*** meadowphysics, this is one to look at
**** basic mode is simple, just subtract by half
**** Reset, Output, and Speeds
     this just needs a speed interface...
     if (config)
**** if rules then choose with encoder 
*** strides
    this one should be easy too, the second half of the grid is just pulled up from an alt key
*** shfts
    a toggle button for the two views
*** cranes
    this is split in two, but horizontally, so going to need to be a little more sophisticated in the mapping
*** ekombi
    just make it half as precise
*** takt
    maybe just a two pager?
*** foulplay
    only 64 ready to go!
*** zellen
    good to go with rows and cols, and adjusting led values
*** isoseq
    just the max pattern length needs to change
